### ISSUE TITLE
能否提供一个设置zotero prefs.js路径的接口

### ISSUE THREAD

**Issue by Amikacin666** [Dorence/utools-thesis-tools#1]
如题，我的zotero为了多平台使用，zotero核心文件目录没有设置在默认地址，能否提供一个插件的配置选项

**Comment by Dorence** [comment]
请问你的报错是
1. "未找到 Zotero Profiles"
2. "未找到 prefs.js 的目录"
3. "未找到 prefs.js"
4. 其他

建议去owner仓库提issue，我这边只是contributor。没fork是因为代码之前不在github托管。
https://github.com/ciaranchen/utools-thesis-tools
